SELECT CONCAT(NAME,'(',SUBSTR(OCCUPATION,1,1),')') AS PERSON
FROM OCCUPATIONS
ORDER BY PERSON;

SELECT CONCAT('There are a total of ',COUNT(OCCUPATION),' ',LOWER(OCCUPATION),'s.') as PROFESSIONAL
FROM OCCUPATIONS
GROUP BY OCCUPATION
ORDER BY PROFESSIONAL;